"""Build .docs-sync-digest/ for the cerberus repo.

cerberus is a Python health monitor. The user-facing surface for docs is
`config/config.yaml`, whose top-level sections (`cerberus`, `tunings`,
`database`) carry one inline-commented key per knob. Those comments are
the de-facto API documentation — they're what the website's docs page
must stay in sync with.

We emit ONE entity per top-level section, with each leaf key as a
documented "parameter". Output format mirrors krkn-hub's so the
website-side parser is shared.

Output:
  - llms.txt       — index (one line per config section)
  - llms-full.txt  — full per-section detail with key tables
  - digest.sha     — sha256 of config/config.yaml for cache invalidation

Pure deterministic Python — no LLM. Bit-identical output for same input.

Run from the cerberus repo root:
    python .docs-sync/build_upstream_digest.py
"""
import argparse
import hashlib
import re
import sys
from pathlib import Path


# The single source-of-truth file we extract from. Adding more sources
# is itself a documentation event — the maintainer should decide whether
# to surface them.
_CONFIG_PATH = Path("config/config.yaml")


# Match a YAML key line at indent level N, with optional value and an
# optional trailing `# comment`. Used line-by-line on `config/config.yaml`.
_KEY_RE = re.compile(
    r"""
    ^
    (?P<indent>\s*)                # leading whitespace
    (?P<key>[a-zA-Z_][a-zA-Z0-9_]*) # the YAML key
    :
    (?P<value>[^#\n]*?)?           # optional inline value (greedy stops at #)
    (?:\s*\#\s*(?P<comment>.*))?   # optional trailing # comment
    \s*$
    """,
    re.VERBOSE,
)


def _yaml_type(raw_value: str) -> str:
    """Infer the value's YAML type from its literal text."""
    v = raw_value.strip()
    if not v:
        return "any"
    low = v.lower()
    if low in ("true", "false"):
        return "bool"
    # Strip surrounding quotes for type detection
    if (v.startswith('"') and v.endswith('"')) or (v.startswith("'") and v.endswith("'")):
        return "string"
    if v.startswith("[") and v.endswith("]"):
        return "list"
    if v.startswith("{") and v.endswith("}"):
        return "map"
    try:
        int(v)
        return "number"
    except ValueError:
        pass
    try:
        float(v)
        return "number"
    except ValueError:
        pass
    return "string"


def parse_config_sections(text: str) -> list[dict]:
    """Parse `config/config.yaml` into a list of top-level sections.

    Each section is `{name, keys: [{name, default, type, description}]}`.
    Only LEAF keys at indent depth 1 (one level under the section) are
    collected — deeply nested values become opaque defaults of their
    parent key.
    """
    sections: list[dict] = []
    current: dict | None = None

    for raw_line in text.splitlines():
        # Stop processing if we hit a blank line followed by another
        # top-level section header — that's handled below.
        stripped = raw_line.strip()
        if not stripped or stripped.startswith("#"):
            continue

        match = _KEY_RE.match(raw_line)
        if not match:
            continue

        indent = match.group("indent") or ""
        key = match.group("key")
        value = (match.group("value") or "").strip()
        comment = (match.group("comment") or "").strip()
        depth = len(indent)

        if depth == 0:
            # Top-level section start
            current = {
                "name": key,
                "description": comment,
                "keys": [],
            }
            sections.append(current)
            continue

        # Nested keys — only depth 1 (immediate children of a section)
        # are collected. Deeper nesting is treated as part of the parent's
        # default value (recorded as type=map).
        if current is None:
            continue
        if depth == 4 or depth == 2:
            # YAML uses either 2 or 4 spaces per indent; accept both at depth 1.
            current["keys"].append({
                "name": key,
                "default": value,
                "type": _yaml_type(value) if value else "any",
                "description": comment,
            })

    return sections


def extract_config_entities(repo_root: Path) -> list[dict]:
    """Return one entity dict per top-level section of config/config.yaml."""
    path = repo_root / _CONFIG_PATH
    if not path.is_file():
        return []
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return []
    return parse_config_sections(text)


def render_llms_txt(entities: list[dict], repo_name: str) -> str:
    lines = [
        f"# {repo_name}",
        "",
        "> Auto-generated by .docs-sync/build_upstream_digest.py.",
        "> Do not edit by hand. Used by the docs-sync agent to detect upstream changes.",
        "",
        "## Config sections",
        "",
    ]
    for e in sorted(entities, key=lambda e: e["name"]):
        n = len(e.get("keys", []))
        lines.append(f"- {e['name']} ({n} key{'s' if n != 1 else ''})")
    return "\n".join(lines) + "\n"


def render_llms_full_txt(entities: list[dict], repo_name: str) -> str:
    """Per-entity detail file. Format mirrors krkn-hub — `## scenario:` is
    the generic entity anchor (here it's a config section)."""
    lines = [
        f"# {repo_name} — full entity details",
        "",
        "> Auto-generated. Source of truth for the cerberus config surface.",
        "",
    ]
    for e in sorted(entities, key=lambda e: e["name"]):
        lines.append(f"## scenario: {e['name']}")
        lines.append("scenario_type: config_section")
        if e.get("description"):
            lines.append(f"description: {e['description']}")
        lines.append("")

        keys = e.get("keys", [])
        if keys:
            lines.append("### parameters")
            lines.append("")
            lines.append("| name | variable | type | default | required | description |")
            lines.append("| ---- | -------- | ---- | ------- | -------- | ----------- |")

            def cell(v):
                return str(v).replace("|", "\\|").replace("\n", " ")

            for k in keys:
                # `variable` mirrors `name` since cerberus YAML doesn't have
                # an env-var convention separate from the key name itself.
                lines.append(
                    f"| {cell(k['name'])} "
                    f"| {cell(k['name'])} "
                    f"| {cell(k['type'])} "
                    f"| {cell(k['default'])} "
                    f"| false "
                    f"| {cell(k['description'])} |"
                )
            lines.append("")
        else:
            lines.append("(no documented keys)")
            lines.append("")
    return "\n".join(lines) + "\n"


def compute_digest_sha(repo_root: Path) -> str:
    h = hashlib.sha256()
    path = repo_root / _CONFIG_PATH
    if path.is_file():
        h.update(str(_CONFIG_PATH).encode("utf-8"))
        h.update(b"\0")
        h.update(path.read_bytes())
        h.update(b"\0")
    return h.hexdigest()


def build_upstream_digest(
    repo_root: Path, output_dir: Path, repo_name: str,
) -> dict:
    entities = extract_config_entities(repo_root)
    output_dir.mkdir(parents=True, exist_ok=True)

    llms = render_llms_txt(entities, repo_name)
    full = render_llms_full_txt(entities, repo_name)
    sha = compute_digest_sha(repo_root)

    (output_dir / "llms.txt").write_text(llms, encoding="utf-8")
    (output_dir / "llms-full.txt").write_text(full, encoding="utf-8")
    (output_dir / "digest.sha").write_text(sha + "\n", encoding="utf-8")

    return {"section_count": len(entities), "digest_sha": sha}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-root", type=Path, default=Path("."))
    parser.add_argument("--output-dir", type=Path, default=Path(".docs-sync-digest"))
    parser.add_argument("--repo-name", default="cerberus")
    args = parser.parse_args(argv)

    if not args.repo_root.is_dir():
        print(f"error: repo root not found: {args.repo_root}", file=sys.stderr)
        return 2

    result = build_upstream_digest(
        repo_root=args.repo_root,
        output_dir=args.output_dir,
        repo_name=args.repo_name,
    )
    print(
        f"Wrote cerberus digest: {result['section_count']} config sections, "
        f"sha={result['digest_sha'][:8]}..."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
